--- #YAML:1.0
name: Digest-SV1
version: 0.01
author: ~
abstract: Cryptosleazically strong message digest format
license: perl
requires:
  Digest: 0
  Digest::Haval256: 0
  Digest::MD5: 0
  Digest::SHA1: 0
provides:
  Digest::SV1:
    file: lib/Digest/SV1.pm
    version: 0.01
generated_by: Module::Build version 0.25
